
spring:
  data:
    mongodb:
      uri: mongodb+srv://sharma_priyanshu:Journal12345@cluster0.00beyc0.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: sharmapriyanshu8488@gmail.com
    password: wbmn dsqq tlop mfgt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080
  servlet:
    context-path: /_journal

weather:
  api:
    key: 9dfd60f9a354d7e796947c3d611f881b

